services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # create tables from schema
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      # seed admin info
      - ./db/seed_admin.sql:/docker-entrypoint-initdb.d/02_seed_admin.sql
      # seed standard users
      - ./db/seed_users.sql:/docker-entrypoint-initdb.d/03_seed_users.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  nextjs:
    build: .
    ports:
      -  '80:3000'
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - mysql

volumes:
  mysql_data: